title: dnd.my
description: Мой личный сборник вкусностей
theme: just-the-docs

url: https://dokudan.github.io/dnd.my

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
